#pragma once
void printintarr(int*, int);
void printdoublearr(double*, int);
int binary_searchInt(int* arr, int size, int k);
void printintmatrix(int* arr[], int rows, int cols);
void printdoublematrix(double* arr[], int rows, int cols);
int* mergeint_arr(int* A, int sizeA, int* B, int sizeb);
void Mergeint(int* arr, int start_a, int end_a, int end_b);
void MergeSortint(int* arr, int start, int end);
int partitionInt(int* arr, int start, int end);
int FixedpartitionInt(int* arr, int start, int end);
void swapint(int* a, int* b);
void quickSortInt(int* arr, int start, int end);
void FixedquickSortInt(int* arr, int start, int end);
void execselector();
void caller();
//exec 1
int exec1();
int hello();
int pi();
int shape();
int math1();
int agecalculator();
int shape2();
int bobcalculator();
int shape2();
int bobcalculator();
int aliceshop();
int wayz();
int printhexa();
//exec 2
int exec2();
int exe2_c1();
int exe2_c2();
int exe2_c3();
int exe2_c4();
int exe2_c5();
int exe2_c6();
int exe2_h1();
int exe2_h2();
int exe2_h3();
int exe2_h4();
int exe2_h5();
int exe2_h6();
int exe2_h7();
int exe2_h8();
int exe2_h9();
//exec3
int exec3();
int exe3_c1();
int exe3_c2();
int exe3_c3();
int exe3_c4();
int exe3_c5();
int exe3_h1();
int exe3_h2();
int exe3_h3();
int exe3_h4();
int exe3_h5();
int exe3_h6();
int exe3_h7();
int exe3_h8();
int exe3_h9();
int exe3_h10();
//exec 4
int exec4();
int exe4_c1();
int exe4_c2();
int exe4_c3();
int exe4_c4();
int exe4_c5();
int exe4_h1();
int exe4_h2();
int exe4_h3();
int exe4_h4();
int exe4_h5();
int exe4_h6();
int exe4_h7();
int exe4_h8();
int exe4_h9();
int exe4_h10();
int exe4_h11();
int exe4_h12();
int exe4_h13();
//exec 5
int exec5();
int exe5_c1();
int exe5_c2();
int exe5_c3();
int exe5_c4();
int exe5_c5();
int exe5_getGCD(int x, int y);
int exe5_h1();
int exe5_square(int x);
int exe5_cube(int x);
int exe5_power(int x, int n);
int exe5_h2();
int exe5_h3();
int exe5_h4();
int exe5_myToLower(char ch);
int exe5_myToUpper(char ch);
int exe5_h5();
int exe5_h6();
int exe5_h7();
int exe5_h8();
int exe5_h9();
int exe5_h10();
int exe5_h11();
//exec 6
void exec6();
int exec6_c1();
int exec6_iseven(int num);
int exec6_c2();
int exec6_fibonr(int n);
int exec6_fibon(int n);
int exec6_c3();
int exec6_c3_A(int n);
int exec6_c3_B(int n);
int exec6_c3_C(int n);
int exec6_c4();
int exec6_c4_a(int n);
int exec6_c5();
int exec6_c5_A(int n);
int exec6_c5_B(int n);
int exec6_c5_C(int n);
int exec6_h1();
//exec7
void exec7();
int exec7_c1();
int exec7_c2();
int exec7_c2_func(int* arr, int n, int* max, int* min, int* sum, double* avg, int* isEven);
int exec7_c3();
int exec7_c3_funcA(int* arr, int n, int* ans);
int exec7_c3_funcB(int* arr, int n, int* ans);
int exec7_c4();
int exec7_c5();
int exec7_c5_func_norec(int* arr, int n);
int exec7_c5_func_rec(int* arr, int n);
int exec7_h1();
int exec7_h1_func(int* max, int* mid, int* min);
double exec7_h2_func(int num, double* digit);
int exec7_h2();
double exec7_h3_func(double* n, double x, double* c);
void exec7_h3();
int exec7_h4();
int exec7_h4_func(int* arr, int n);
int exec7_h5();
int exec7_h5_func(int* arr, int n, int key, int* pnum1, int* pnum2);
void exec7_h6_func(int* arr, int n, int* maxeven, int* even, int* maxodd, int* odd);
int exec7_h6();
int exec7_h7();
int exec7_h7_rec(int*, int);
int exec7_h7_norec(int*, int);
int exec7_h8();
void exec7_h8_func_A(int* arr, int n);
void exec7_h8_func_B(int* arr, int n);
int exec7_h9();
double exec7_h9_func(int* arr, int n);
int exec7_h10();
int exec7_h10_func(double* arr, int n);
int exec7_h11_func_rec(int* arr, int n);
int exec7_h11_func(int* arr, int n);
int exec7_h11();
//h8
void exec8();
int exec8_c1();
int* exec8_c1_makearry(int size);
int exec8_c2();
int* exec8_c2_fibo(int n);
int exec8_c3();
int exec8_c3_func(int* arr, int size, int* times);
int exec8_c4();
int exec8_c4_func(int* arr, int size, int k);
int exec8_c5_func(int* arr, int n, int a, int b);
int exec8_c5();
int* exec8_h1_func(int size);
int exec8_h1();
int exec8_h2();
int exec8_h2_func(int* arr, int* size, int isEven);
int* exec8_h3_func(int* A, int* B);
int exec8_h3();
void exec8_h4_func(int* arr, int n);
int exec8_h4();
int* exec8_h5_func(int* arr, int* n);
int exec8_h5();
int exec8_h6_func(int* arr, int n);
int exec8_h6();
int exec8_h7_func(int* arr, int n);
int exec8_h7();
int exec8_h8_func(int* arr, int n);
int exec8_h8();
int exec8_h9_func(int* arr, int n, int amount);
int exec8_h9();
void exec8_h10_func(int* arr, int n);
int exec8_h10();
//h9
void exec9();
char* exec9_c1_func(char* arr);
int exec9_c1();
char exec9_c2_func(char* arr, int* amount);
int exec9_c2();
int exec9_c3();
int exec9_c3_func(int* arr, int size, int* times);
int exec9_c4_func(int* arr, int size, int k);
int exec9_c4();
int exec9_c5_func(int* arr, int n, int a, int b);
int exec9_c5();
int* exec9_h1_func(int size);
int exec9_h1();
int exec9_h2_func(int* arr, int* size, int isEven);
int exec9_h2();
int* exec9_h3_func(int* a, int* b);
int exec9_h3();
void exec9_h4_func(int* arr, int n);
int exec9_h4();
int* exec9_h5_func(int* arr, int* n);
int exec9_h5();
int exec9_h6_func(int* arr, int n);
int exec9_h6();
int exec9_h7_func(int* arr, int n);
int exec9_h7();
int exec9_h8_func(int* arr, int n);
int exec9_h8();
void exec9_h9_func(int* arr, int n, int amount);
int exec9_h9();
void exec9_h10_func(int* arr, int n);
int exec9_h10();